// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYE2lK8JZkou3sdfo34bPjyrqFu_jPOHc',
    appId: '1:724135522573:web:5c395723b5af2be5810044',
    messagingSenderId: '724135522573',
    projectId: 'fasum-c01a9',
    authDomain: 'fasum-c01a9.firebaseapp.com',
    storageBucket: 'fasum-c01a9.appspot.com',
    measurementId: 'G-9TVCRVRWLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuekotd3jaMlpBrFWjSHQzTsMYuGrkY64',
    appId: '1:724135522573:android:78a897742676e694810044',
    messagingSenderId: '724135522573',
    projectId: 'fasum-c01a9',
    storageBucket: 'fasum-c01a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7g9IcbQ_8ADn9ziQ8nXr8oaHmQgxgMV4',
    appId: '1:724135522573:ios:f79ca7f1314b6897810044',
    messagingSenderId: '724135522573',
    projectId: 'fasum-c01a9',
    storageBucket: 'fasum-c01a9.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7g9IcbQ_8ADn9ziQ8nXr8oaHmQgxgMV4',
    appId: '1:724135522573:ios:6463e86d522cabed810044',
    messagingSenderId: '724135522573',
    projectId: 'fasum-c01a9',
    storageBucket: 'fasum-c01a9.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
