// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9AtRbrsEBkMKkiHG6CGd45WCvEA8cjgE',
    appId: '1:872385993196:web:2d250dc727da00b68e48c9',
    messagingSenderId: '872385993196',
    projectId: 'first-app-662c2',
    authDomain: 'first-app-662c2.firebaseapp.com',
    databaseURL: 'https://first-app-662c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-662c2.appspot.com',
    measurementId: 'G-9C379YYJ63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlLLdfhlG2B2VunLJlaDszMMs4KeDjTOc',
    appId: '1:872385993196:android:df83e3c1b99b8d088e48c9',
    messagingSenderId: '872385993196',
    projectId: 'first-app-662c2',
    databaseURL: 'https://first-app-662c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-662c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXSD4hkbSfsXPQJ6dJeCZnoTVl5YP4ttA',
    appId: '1:872385993196:ios:56aa4180352f78ea8e48c9',
    messagingSenderId: '872385993196',
    projectId: 'first-app-662c2',
    databaseURL: 'https://first-app-662c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-662c2.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXSD4hkbSfsXPQJ6dJeCZnoTVl5YP4ttA',
    appId: '1:872385993196:ios:d95af734954d2a448e48c9',
    messagingSenderId: '872385993196',
    projectId: 'first-app-662c2',
    databaseURL: 'https://first-app-662c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-662c2.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
